name: Build and Deploy Docs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-docs:
    name: Build and deploy docs
    uses: bmazzarol/bmazzarol/.github/workflows/build-deploy-docs.yml@main
    with:
      docsProjectPath: Eon.Docs
      csProjFileName: Eon.Docs.csproj
