name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: bmazzarol/bmazzarol/.github/actions/ci-build@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          sonarProjectKey: bmazzarol_Eon
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() && github.event_name == 'pull_request' }}
        with:
          files: |
            **/test-results.trx